- style.css
- website.html
Please add my file to your repository with the label of hacktoberfest
> hacktoberfest2022

- style.css
- website.html
I have added Neon Hover effect to buttons
> Added Neon Hover effect to buttons

- Code 1
> Create Code 1

- krisshx.py
In this program i have printed all prime number in an interval
> Hacktober Fest 2022

- Angle.cpp
- Intersection.cpp
1. Angle-takes input and finds an angle of a triangle
2. Intersection-Coordinates of intersection of two lines
> HacktoberFestRohit Yadav

- Tribute Webpage/index.html
- Tribute Webpage/styles.css
Please merge this pull request into your repository
> Tribute Page 

- C++Factorial.cpp
> hacktoberfest 2022

- Bucket_Sort.cpp
Please review and merge the PR for Hacktoberfest
> Added Bucket Sort

- CalculatorAddition.java
it will add 2 numbers that you will input
> calculator for addition

- ConnectFourGame/index.html
- ConnectFourGame/script.js
- ConnectFourGame/style.css
A 2 player Connect four game added , kindly accept my PR
> Connect four game added

- Kadanes.java
Please merge this with hacktoberfest-accepted label.
> Added Kadanes Algorithm

- Krishnamurthy.java
Please merge with hacktoberfest-accepted tag.
> Added Krishnamurthy number.

- webpage.html
> hacktober-2022

- snakegame.py
I created a snake game using python programming language. Hope you all liked it.
> Created a snake game using python

- Req 1
> Create Req 1

- request 5
> Create request 5

- Req 4
> Create Req 4

- paintgui.cpp
This is a mini project (paintgui) made using opengl  in which you can draw different polygons and shapes in different colours.
> Paint like GUI using opengl

- SasakisAlgo.c
This is the implementation of sasaki sorting algorithm for distributed sorting.
> Sasaki Sorting Algorithm

- Tic-Tac-Toe Python/game.py
> tic tac toe game added

- Dijkstra_algorithm.cpp
Thank you for reading my pull request.
Added Dijkstra Algorithm in C++.
> Added Greedy Algorithm (Dijkstra) in C++

- htmlwebs.html
i have added internal css with image and colors.
> Update added internalcsshtmlwebs.html

- to-do-list/README.md
- to-do-list/index.html
- to-do-list/script.js
- to-do-list/style.css
Hey @dharmanshu9930 , I have added the to do list website. Kindly check it and review it. 
Thank you.
> Added to-do-list website 

- linear search algo
created a linear search through c++.
> created linear search algo

- play_code_c++.cpp
> Hacktoberfest-2022

- smith.java
A Smith number is a composite number whose sum of digits equals to the sum of digits of its prime factors, excluding 1.
> SMITH NUMBER

- QuickSort.cpp
Sorts array of elements in O(n log n) time.
> Added QuickSort program

- ARRAY 4.cpp
> Hactoberfest 2022

- GymWebsite/indexOnly.html
- GymWebsite/style.css
I just split the main files in two, for more understanding.
> Reorganization of files

- signup-form/index.html
- signup-form/scripts.js
- signup-form/style.css
> Add Sign up page

- Random-colour-generator/index.html
Issue #242 solved
I have created a random colour generating website on refresh.
Please accept it under hacktoberfest2022
> Random colour generating website

- calculator/README.md
- calculator/calculator.cpp
- calculator/calculator.h
- calculator/main.cpp
- calculator/makefile
- calculator/scientific.cpp
- calculator/scientific.h
- countingsort.cpp
I have uploaded the code of counting sort in c++.
> Counting Sort

- Random Color Generator/File.html
> Added Random Color Generator Website

- rat_in_maze.cpp
> Rat_in_maze

- divisible by 2 3.cpp
> hactoberfest2022

- navbar.html
please accept my pull request and add hactoberfest2022 label
> Updateadd navigationbar navbar.html

- Hacktoberfest2022.html
please accept my pull request and add hactoberfest2022 label
> Updatesimplewebsite Hacktoberfest2022.html

- aggressive_cow.cpp
updated this for hacktoberfest2022.
> Aggressive Cow

- Stopwatch/index.html
- Stopwatch/index.js
- Stopwatch/styles.css
Added the stopwatch webapp which uses HTML,CSS and JavaScript.
> Added the stopwatch webapp

- Customer-Segmentation/Customer Segmentation.ipynb
- Titanic-survivor-prediction/Kaggle Titanic.ipynb
I have added Customer Segmentation of a Super Market using K Means Clustering
> Added Customer Segmentation of a Super Market

- numberpattern3.java
> Added a new number pattern

- Linear_Search.c
Please accept it under Hacktoberfest2022 if it's ok
> Add Linear search

- half_pyramid.java
> added java program

- base-apparel-coming-soon-master/index.html
- base-apparel-coming-soon-master/style.css
Hey there, it's my first time contributing to this project. In this contribution I have added some more styling in the project developed by Ayush and the style.css is prettified by the VS code editor by default.
> adding more styling to the project developed by Ayush

- calculator.cpp
> To calculate num in cpp

- chess.css
- chess.html
- chess.js
Please accept my chess game for hacktober fest, thank you
> Please accept my chess game for hacktober fest
